
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jamilly
 */
public class CaixaEntradaSaidaFrame extends javax.swing.JFrame {
    private MensagemTableModel tbModel;
    private int op; //entrada == 0, saída == 1 ou lixeira == 2
    private Usuario user;
    private Funcao funcoes;
        
    
    public CaixaEntradaSaidaFrame(Usuario user, int op){
        this.user = user;
        initComponents();
        this.op = op;
        funcoes= new Funcao();
        tbModel = new MensagemTableModel();
        tbMensagem.setModel(tbModel);
        tbMensagem.setSelectionBackground(new Color(191, 106, 106));
        
        if(this.op == 0){ //Entrada
            //botao.setVisible(false);
            tbModel.carregarDadosEntrada(user); 
            
        }if(this.op == 1){ 
            header.setText("Caixa de Saída");
            caixaSaida.setVisible(false);
            enviarNova.setVisible(false);
            tbModel.carregarDadosSaida(user);
            lixo.setVisible(false);
            
        }if(this.op == 2){
            header.setText("Lixeira");
            tbModel.carregarLixeira(user);
            caixaSaida.setVisible(false);
            enviarNova.setVisible(false);
            abrir.setVisible(false);
            lixo.setVisible(false);
            excluir.setText("Restaurar");
        }
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMensagem = new javax.swing.JTable();
        caixaSaida = new javax.swing.JButton();
        enviarNova = new javax.swing.JButton();
        abrir = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        botao = new javax.swing.JButton();
        lixo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jPanel2.setBackground(new java.awt.Color(249, 247, 248));

        header.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        header.setForeground(new java.awt.Color(102, 0, 0));
        header.setText("Caixa de Entrada");

        logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(102, 0, 0));
        logout.setText("<< log out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(header)
                    .addComponent(logout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbMensagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbMensagem.setAutoscrolls(false);
        tbMensagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMensagemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMensagem);

        caixaSaida.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        caixaSaida.setForeground(new java.awt.Color(102, 0, 0));
        caixaSaida.setText("Mensagens enviadas");
        caixaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSaidaActionPerformed(evt);
            }
        });

        enviarNova.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enviarNova.setForeground(new java.awt.Color(102, 0, 0));
        enviarNova.setText("Enviar nova mensagem");
        enviarNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarNovaActionPerformed(evt);
            }
        });

        abrir.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        abrir.setForeground(new java.awt.Color(102, 0, 0));
        abrir.setText("Abrir mensagem");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });

        excluir.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        excluir.setForeground(new java.awt.Color(102, 0, 0));
        excluir.setText("Excluir mensagem");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        botao.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        botao.setForeground(new java.awt.Color(102, 0, 0));
        botao.setText("Voltar");
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        lixo.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        lixo.setForeground(new java.awt.Color(102, 0, 0));
        lixo.setText("Lixeira");
        lixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lixoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(caixaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botao, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(enviarNova, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lixo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao)
                    .addComponent(excluir)
                    .addComponent(abrir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarNova)
                    .addComponent(lixo)
                    .addComponent(caixaSaida))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarNovaActionPerformed
       CadastroMensagemFrame mensagem = new CadastroMensagemFrame(user);
       mensagem.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_enviarNovaActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        if (tbMensagem.getSelectedRowCount() != 0){
            setVisible(false);
            int id = tbModel.getMensagem(tbMensagem.getSelectedRow()).getId();
                if(op == 0){
                    VisualizarMensagemFrame visualiza = new VisualizarMensagemFrame(id, user,0);
                    visualiza.setVisible(true);
                }else{
                    VisualizarMensagemFrame visualiza = new VisualizarMensagemFrame(id, user,1);
                    visualiza.setVisible(true);
                }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma mensagem");
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void caixaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSaidaActionPerformed
        CaixaEntradaSaidaFrame saida = new CaixaEntradaSaidaFrame(user, 1);
        saida.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_caixaSaidaActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        LoginFrame login = new LoginFrame();
        setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        if (tbMensagem.getSelectedRowCount() != 0){
            int id = tbModel.getMensagem(tbMensagem.getSelectedRow()).getId();
            Mensagem m = funcoes.encontraMensagem(id);
                       
                if(op == 0){//caixa de entrada
                    m.setViewDestinatario(0);
                    funcoes.apaga(m);
                    tbModel.carregarDadosEntrada(user);
                    
                }if(op == 1){//caixa de saída
                    m.setViewRemetente(0);
                    funcoes.apaga(m);
                    tbModel.carregarDadosSaida(user);  
                    
                }if(op == 2){
                    m.setViewDestinatario(1);
                    funcoes.apaga(m);
                    tbModel.carregarLixeira(user); 
                }
                
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma mensagem");
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        if(op == 0){
            LoginFrame l = new LoginFrame();
            l.setVisible(true);
            setVisible(false);
        }else{
            CaixaEntradaSaidaFrame entrada = new CaixaEntradaSaidaFrame(user, 0);
            setVisible(false);
            entrada.setVisible(true);
        }
    }//GEN-LAST:event_botaoActionPerformed

    private void lixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lixoActionPerformed
        CaixaEntradaSaidaFrame lixeira = new CaixaEntradaSaidaFrame(user, 2);
        setVisible(false);
        lixeira.setVisible(true);
    }//GEN-LAST:event_lixoActionPerformed

    private void tbMensagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMensagemMouseClicked
        if (evt.getClickCount() == 2) { //ia fazer isso e não deu tempo
        }
    }//GEN-LAST:event_tbMensagemMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton botao;
    private javax.swing.JButton caixaSaida;
    private javax.swing.JButton enviarNova;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lixo;
    private javax.swing.JLabel logout;
    private javax.swing.JTable tbMensagem;
    // End of variables declaration//GEN-END:variables
}
